Remove PdgParticle.is_generic
We no longer have generic Particles, just generic Items. The leftover
use of is_generic (which was changed to indicate whether a state is
self-conjugate) in utils.best was causing, e.g., the following failure:

In [2]: import pdg

In [3]: api = pdg.connect()

In [4]: p = api.get_particle_by_mcid(113)

In [5]: p.mass
---------------------------------------------------------------------------
PdgAmbiguousValueError                    Traceback (most recent call last)
Cell In[5], line 1
----> 1 p.mass

File ~/physics/pdg/api/pdg/particle.py:403, in PdgParticle.mass(self)
    400 @property
    401 def mass(self):
    402     """Mass of the particle in GeV."""
--> 403     best_mass_property = best(self.masses(), self.api.pedantic, '%s mass (%s)' % (self.name, self.pdgid),
    404                               self.is_generic)
    405     return best_mass_property.best_summary().get_value('GeV')

File ~/physics/pdg/api/pdg/utils.py:83, in best(properties, pedantic, quantity, is_generic)
     81     if is_generic:
     82         err += '. This is a generic charge state; try selecting a specific charge (e.g. by setting the MC ID)'
---> 83     raise PdgAmbiguousValueError(err)
     84 else:
     85     props_best = [p for p in props_without_alternates if 'D' in p.data_flags]

PdgAmbiguousValueError: Ambiguous best property for rho(770)0 mass (M009/2023). This is a generic charge state; try selecting a specific charge (e.g. by setting the MC ID)

Removing PdgParticle.is_generic and its use in utils.best fixes this
case and doesn't cause any tests to fail.